/**
 * Constantes métier globales — tirées de ENV.
 */
import { ENV } from './env';
import { STORAGE_KEYS } from '@/storage/authStorage';

export const CONSTANTS = {
  // Tontine
  MIN_CONTRIBUTION_FCFA: ENV.MIN_CONTRIBUTION_FCFA,
  MAX_MEMBERS: ENV.MAX_MEMBERS_PER_TONTINE,

  // Auth
  PIN_LENGTH: ENV.PIN_LENGTH,
  MAX_LOGIN_ATTEMPTS: ENV.MAX_LOGIN_ATTEMPTS,
  OTP_TTL_SECONDS: ENV.OTP_TTL_SECONDS,
  SESSION_TIMEOUT_MS: ENV.SESSION_TIMEOUT_MS,
  ACCESS_TOKEN_TTL_MIN: 15,
  REFRESH_TOKEN_TTL_DAYS: 30,

  // UI
  COUNTRY_CODE: ENV.COUNTRY_CODE,
  CURRENCY: ENV.CURRENCY,
  DEFAULT_LANG: ENV.DEFAULT_LANG,

  STORAGE_KEYS,

  // Score Kelemba
  SCORE_MIN: 0,
  SCORE_MAX: 1000,
  SCORE_BAN_THRESHOLD: 0,

  // Paiements — statuts
  PAYMENT_STATUS: {
    PENDING: 'PENDING',
    PROCESSING: 'PROCESSING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
  },
} as const;
